import { LogMessage } from './types';

// These serve as the few-shot examples for Gemini
export const SEED_MESSAGES: string[] = [
  "[NAV] Calibration complete. North Star lock-in at 99.8%.",
  "[UAS] Drone Swarm Alpha deploying from Sleigh Mothership. Formation: V-Shape.",
  "[USV] DriX unit 04 reporting wave height 2m. Hydrofoil stabilizers active.",
  "[GLIDER] Slocum G3 surfacing for Iridium satellite uplink. Salinity nominal.",
  "[SYS] Detected low cheer levels in Sector 7. Deploying emergency carols.",
  "[UAS] Battery cell temp on Scout-1 within operational limits. Rotor RPM 8500.",
  "[ENG] Magic flux capacitor requires cookie input.",
  "[USV] Obstacle avoidance engaged. Iceberg detected at bearing 330.",
  "[NAV] Wind shear warning over Atlantic. Adjusting altitude to Flight Level 350.",
  "[GLIDER] Pitch attitude adjusted for deep dive cycle. Buoyancy engine active.",
  "[CARGO] Toy sack compression ratio holding steady at 4000:1.",
  "[BIO] Rudolph nose luminosity adjusted to 8000 lumens (Fog Mode).",
  "[SEC] Chimney diameter scan initiated. Soot filters engaged.",
  "[UAS] Lidar point cloud generated for rooftop landing zone.",
  "[SYSTEM CHECK] Reindeer Bio-Harness: DASHER heart rate nominal.",
  "[SYSTEM CHECK] Reindeer Bio-Harness: BLITZEN sugar levels high.",
  "[POWER] Antimatter Cookie Reactor Status: STABLE (98%).",
  "[CARGO] Naughty/Nice Algorithm v25.12: PROCESSING.",
    "[ASSET_HEALTH] Elf Operator #17: CAFFEINE LEVELS LOW. Deploying emergency cocoa.",
    "[UXS LINK] Glider-7 connection lost under North Pole ice cap.",
    "[ALERT] Coal dispenser hopper jammed.",
    "[GPS_LOCK] Global Positioning Sleigh (GPS) Signal Quality: Nominal.",
    "[CARGO_SENSOR] Toy Mass Density Shift: MINOR. Recalibrating Center of Gravity (CG).",
    "[ROUTINE_TASK] Command: CHECK MILK & COOKIES STATUS at coordinates 38°N, 77°W.",
    "[TELEMETRY_LINK] Sleigh-to-Ops Center Link Status: 100% RELIABLE.",
    "[VEHICLE_HEALTH] DriX Candy Cane Stripe: HULL INTEGRITY 99%.",
    "[AIR_TEMP] -1.5°C (Hot Chocolate Warmers Active).",
    "[DELIVERY_FAIL] Package 404: Address Not Found (Naughty List Override?).",
    "[THERMAL_SCAN] Anomaly Detected: FIREPLACE ACTIVE in Sector 7. Re-route deployment vector.",
    "[SONAR_PING] Sub-bottom Profiler: Detecting SUNKEN GINGERBREAD HOUSE at 15m.",
    "[SYSTEM_OVERRIDE] Pilot Request: Manual activation of RUDOLPH FOG LAMPS.",
    "[LOG_DATA] COOKIE CONSUMPTION database size: 4.8 TB and rapidly growing.",
    "[SECURITY_ALERT] Unidentified autonomous system (UAS) detected - enable Grinch check.",
    "[NAV_WARNING] Roof pitch exceeds 45 degrees. Deploying anti-slip landing gear.",
    "[PAYLOAD_DROP] Chimney aperture narrow. Initiating 'Magic Squeeze' compression algorithm.",
    "[FUEL_STATUS] Reindeer carrot reserves at 15%. Refuel scheduled at next pit stop.",
    "[SONAR_CONTACT] Passive Acoustics: Detecting whale vocalizations (Type: Caroling).",
    "[GLIDER_DATA] Salinity Anomaly: Ocean composition currently 5% Eggnog.",
    "[AIRSPACE] TFR (Temporary Flight Restriction) active over Whoville mountains.",
    "[SYSTEM_ERROR] NAUGHTY_LIST.dat buffer overflow. Too many entries this year.",
    "[DRONE_DEPLOY] Scout UAS 'Jingle-1' launched for roof structural integrity scan.",
    "[HULL_STRESS] Sleigh runner friction warning. Deploying coolant.",
    "[SENSOR_CAL] NOSE_RED luminescence calibration: Output steady at 1200 Lumens.",
    "[COMMS] Intercepted civilian transmission: 'Grandma got run over...' (False Alarm).",
    "[PILOT_ALERT] High G-Force turn detected. Santa belly oscillation damping active.",
    "[OCEAN_OPS] CTD Cast Complete. Conductivity: High. Temperature: Frigid. Spirit: Jolly.",
    "[WEATHER] Whiteout conditions in Sector 4. Switching to Instrument Flight Rules (IFR).",
    "[ELF_CHAT] Operator #04: 'Who took my headset?' [HR TICKET LOGGED].",
    "[ASSET_TRACK] DriX 'Mistletoe' holding station for relay support in North Atlantic.",
    "[TARGET_LOCK] Stocking heat signature acquired. Trajectory calculated.",
    "[POWER_GRID] Workshop Main Turbine: Spooling up for midnight production surge.",
    "[BIO_READING] Santa stress levels rising. Auto-playing 'Silent Night' for calm.",
    "[CARGO_SHIFT] WARNING: 'Dollhouse' payload unstable. Tightening cargo straps.",
    "[RADAR_CONTACT] Unidentified Sleigh Object. ID confirmed: Easter Bunny (Non-threat).",
    "[FLIR_IMG] Thermal signature detected: YETI moving in Himalayan Sector.",
    "[DATA_LINK] Downloading 'Nice List' Patch v2.1 (Last minute edits included).",
    "[PROPULSION] Dasher/Dancer gait synchronization error. Re-aligning harness.",
    "[MISSION_CLOCK] TIME REMAINING: 4 Hours to Sunrise. Increase velocity to Mach 2.",
    "[AERO_DYNAMICS] Drag coefficient spike detected. Cause: Pilot's beard turbulence.",
    "[BATTERY_MGMT] Glider-9 Li-Po cells critical. Recharging via Northern Lights induction.",
    "[PAYLOAD_LOG] Coal dust filter capacity at 90%. Change filter immediately.",
    "[SONAR_SWEEP] Multi-beam echo sounder mapping 'Island of Misfit Toys' coastline.",
    "[NAV_VECTOR] Banking hard left to avoid collision with ISS (International Space Station).",
    "[SECURITY] Firewall Attack: 'The_Grinch' attempting to hack Naughty List database.",
    "[OPTICAL_CAM] Visual confirmation: Frosty the Snowman moving at 3 knots.",
    "[LANDING_GEAR] Skid friction warning. Roof shingles are loose at Target 104.",
    "[CHEM_ANALYSIS] Milk sample at 123 Maple St: 2% Fat. Cookie type: Oatmeal Raisin.",
    "[AUTOPILOT] Engaging 'Chimney Dive' sequence. Precision: +/- 2cm.",
    "[DATA_STREAM] Ingesting 50 Petabytes of 'Wish List' emails. Server cooling active.",
    "[PROP_CHECK] DriX starboard thruster jammed with tinsel. Reversing polarity.",
    "[RELATIVITY] Time Dilation Drive: Active. Compressing 6 hours into 30 minutes.",
    "[CARGO_ASSEMBLY] Automated assembly arm failure. Bicycle wheel installed on toaster.",
    "[WEATHER_RADAR] Doppler indicates 'Blizzard of '96' levels in Buffalo. rerouting.",
    "[ELF_TRACKER] Elf Team 6 deployed for emergency toy repair in Sector 9.",
    "[HULL_INTEGRITY] Sleigh clear coat scratched. Blaming low-hanging satellite.",
    "[LIDAR_SCAN] Tree topology mapped. Ornament density: HIGH.",
    "[SUPPLY_CHAIN] Scotch Tape reserves critical. Diverting logistics drone.",
    "[COMMS_CHATTER] Intercept: 'I saw Mommy kissing Santa Claus.' Disregarding as hallucination.",
    "[ENERGY_READING] Holiday Spirit Levels: 110%. Overclocking engines.",
    "[DEICING] Wing leading edges accumulating frost. Deploying heated glycol spray.",
    "[MISSION_ABORT] Target House has no chimney. Deploying 'Master Key' Protocol.",
    "[SYS_ADMIN] Who changed the password to 'Rudolph123'? Insecure.",
    "[GEODESY_DATA] North Pole magnetic drift exceeding nominal parameters. Adjusting compass.",
    "[GLIDER_ALERT] Glider-12 reporting encounter with a submerged Christmas tree farm.",
    "[FLUID_DYNAMICS] Hot Cocoa Dispenser pressure: LOW. Increasing pump rate.",
    "[NAVIGATION] Waypoint 'Xmas_1987' logged successfully. Commencing next leg.",
    "[DATA_CAPTURE] High-resolution imagery of gingerbread house architectural details acquired.",
    "[SENSOR_FAULT] Primary Optical Sensor fouled with whipped cream residue. Manual clean required.",
    "[SECURITY_PATCH] Applied fix for 'Krampus Ransomware' vulnerability on Sleigh OS.",
    "[AIR_SPEED] Warning: Speed exceeding Mach 1. Deploying sonic boom dampeners.",
    "[OPS_MANUAL] Referencing Section 4.3: Protocol for handling live reindeer stampedes.",
    "[COMMS_CHECK] Testing emergency broadcast frequency: 'HO HO HO' transmitted.",
    "[RESOURCE_MGMT] Deploying smaller UAS for surveillance of cookie procurement logistics.",
    "[SYSTEM_RESTORE] Recovered backup data: Missing toy file from 2005 restored.",
    "[DELIVERY_SYSTEM] Automated Wrapping Module #3 reports paper jam. Bypass active.",
    "[VEHICLE_MAINT] Performing mid-flight defrost cycle on main fuselage and skid rails.",
    "[ELF_SUPPORT] Requesting immediate drone delivery of specialized tools for 'Teddy Bear' assembly.",
    "[ACOUSTIC_REC] Hydrophone detected faint melody: 'Feliz Navidad' at 500 meters depth.",
    "[WARNING] System integrity compromised by excess festive glitter particulates.",
    "[THERMAL_IMAGERY] Target home appears vacant. Deploying 'Key Under Mat' protocol.",
    "[PROPULSION_SYNC] Vixen and Comet thrust differential 5%. Engaging auto-trim.",
    "[LOG_DATA] Recording pilot commentary: 'Twas the night before Christmas...' data file initiated.",
    "[WEATHER_SCAN] Detecting localized 'Snow Globe Effect' precipitation in Sector 3.",
    "[UXS_LINK] DriX reporting successful deployment of underwater mistletoe cluster.",
    "[POWER_DRAIN] Excessive current draw on 'LED Decoration' circuit. Failsafe engaged.",
    "[ENVIRONMENTAL] Monitoring atmospheric dust: High concentration of cinnamon and nutmeg.",
  "[FLIGHT_PLAN] Deviation necessary to avoid migrating flock of candy cane birds.",
];

export const SYSTEMS = ["NAV", "ENG", "GIFT", "HULL", "SYS", "CARGO", "BIO", "SEC", "ELF", "UAS", "USV", "GLIDER"];

export const SYSTEM_COLORS = {
  NAV: "text-blue-400",
  ENG: "text-orange-400",
  GIFT: "text-pink-400",
  HULL: "text-gray-400",
  SYS: "text-green-400",
  CARGO: "text-yellow-400",
  BIO: "text-red-400",
  SEC: "text-purple-400",
  ELF: "text-emerald-400",
  UAS: "text-cyan-400",
  USV: "text-indigo-400",
  GLIDER: "text-teal-400",
};